//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserAccount
    {
        public int ID { get; set; }
        public string USERAD { get; set; }
        public string USERSOYAD { get; set; }
        public Nullable<int> USERYAS { get; set; }
        public string USERMAIL { get; set; }
        public Nullable<System.DateTime> USERDOGUMTARIHI { get; set; }
        public string USEROKUL { get; set; }
        public Nullable<int> USERDENEYIM { get; set; }
        public Nullable<bool> USERSTATUS { get; set; }
        public string USERNICK { get; set; }
        public string USERPASSWORD { get; set; }
    }
}
